import {beforeEach,describe,expect,it,vi} from "vitest";
import {useAttemptStore} from "./useAttemptStore";
import * as api from "@/lib/api";
vi.mock("@/lib/api",()=>({startSession:vi.fn(),getAttempt:vi.fn(),patchAttempt:vi.fn(),submitAttempt:vi.fn()}));
const attempt=(id:string,solution="server")=>({id,problem_id:"p1",status:"draft" as const,solution_markdown:solution,revision:2,elapsed_seconds:5,started_at:"2026-09-06T08:00:00Z",updated_at:"2026-09-06T08:05:00Z",submitted_at:null});
const learning=(value:ReturnType<typeof attempt>)=>({session_id:`s-${value.id}`,problem_id:"p1",problem_title:"Problem",status:"active" as const,created_at:value.started_at,updated_at:value.updated_at,started_at:value.started_at,completed_at:null,duration_seconds:5,number_of_attempts:1,number_of_tutor_interactions:0,outcome:null,problem:null,attempts:[value],current_attempt_id:value.id,final_work:value.solution_markdown,tutor_assessment:null,resource_recommendation:null});
describe("server-authoritative attempt restore",()=>{
 beforeEach(()=>{localStorage.clear();vi.clearAllMocks();useAttemptStore.getState().reset()});
 it("ignores a stale legacy currentAttempt identity",async()=>{localStorage.setItem("khollelab.currentAttempt.p1","old-submitted");const current=attempt("new-current");vi.mocked(api.startSession).mockResolvedValue(learning(current));await useAttemptStore.getState().load("p1");expect(api.getAttempt).not.toHaveBeenCalled();expect(useAttemptStore.getState()).toMatchObject({sessionId:"s-new-current",attemptId:"new-current",solution:"server"})});
 it("recovers only a newer draft belonging to the server-selected attempt",async()=>{localStorage.setItem("khollelab.draft.old",JSON.stringify({solution:"old draft",updatedAt:"2026-09-06T09:00:00Z",serverRevision:1}));localStorage.setItem("khollelab.draft.new",JSON.stringify({solution:"recover me",updatedAt:"2026-09-06T09:00:00Z",serverRevision:1}));const current=attempt("new");vi.mocked(api.startSession).mockResolvedValue(learning(current));await useAttemptStore.getState().load("p1");expect(useAttemptStore.getState().recovery).toBe("recover me");expect(useAttemptStore.getState().solution).toBe("server")});
 it("preserves local text when a later session request fails",async()=>{const current=attempt("new");vi.mocked(api.startSession).mockResolvedValueOnce(learning(current)).mockRejectedValueOnce(new Error("offline"));await useAttemptStore.getState().load("p1");useAttemptStore.getState().updateSolution("offline draft");await useAttemptStore.getState().load("p1");expect(useAttemptStore.getState()).toMatchObject({solution:"offline draft",saveState:"error",attemptId:"new"})});
});
