"use client";
import {FormEvent,useState} from "react";
import type {Account} from "@/lib/api";
import {changePassword,claimAnonymousHistory,loginAccount,logoutAllAccounts,registerAccount} from "@/lib/api";

export function AccountDialog({account,onAccount,onClose}:{account:Account;onAccount:(value:Account)=>void;onClose:()=>void}){
 const[mode,setMode]=useState<"login"|"register">("login"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{const next=mode==="login"?await loginAccount(String(data.get("email")),String(data.get("password"))):await registerAccount({email:String(data.get("email")),password:String(data.get("password")),display_name:String(data.get("display_name")||""),claim_anonymous_history:data.get("claim")==="on"});onAccount(next)}catch(value){setError(value instanceof Error?value.message:"Une erreur est survenue.")}finally{setBusy(false)}}
 if(account.authenticated)return <div className="modal-backdrop"><section className="account-dialog" role="dialog" aria-modal="true" aria-label="Mon compte"><button className="dialog-close" onClick={onClose} aria-label="Fermer">×</button><h2>Mon compte</h2><strong>{account.display_name||"Compte KHOLLELAB"}</strong><p>{account.email}</p>{account.created_at&&<p>Compte créé le {new Date(account.created_at).toLocaleDateString("fr-FR")}</p>}{account.anonymous_sessions_available>0&&<div className="claim-offer"><p>Cet appareil contient {account.anonymous_sessions_available} séance(s) anonyme(s). Voulez-vous les rattacher à votre compte ?</p><button onClick={async()=>{await claimAnonymousHistory();onAccount({...account,anonymous_sessions_available:0})}}>Rattacher</button><button onClick={()=>onAccount({...account,anonymous_sessions_available:0})}>Ignorer</button></div>}<form onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await changePassword(String(data.get("current")),String(data.get("next")));setError("Mot de passe modifié.")}catch(value){setError(value instanceof Error?value.message:"Erreur")}}}><h3>Changer le mot de passe</h3><input name="current" type="password" placeholder="Mot de passe actuel" required/><input name="next" type="password" minLength={12} maxLength={128} placeholder="Nouveau mot de passe" required/><button>Modifier</button></form><button className="danger" onClick={async()=>{await logoutAllAccounts();onAccount({authenticated:false,anonymous_sessions_available:0});onClose()}}>Se déconnecter de tous les appareils</button>{error&&<p role="alert">{error}</p>}</section></div>;
 return <div className="modal-backdrop"><section className="account-dialog" role="dialog" aria-modal="true" aria-label="Authentification"><button className="dialog-close" onClick={onClose} aria-label="Fermer">×</button><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Connexion</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Créer un compte</button></div><form onSubmit={submit}>{mode==="register"&&<label>Nom / pseudo (facultatif)<input name="display_name" autoComplete="nickname"/></label>}<label>Adresse e-mail<input name="email" type="email" autoComplete="email" required/></label><label>Mot de passe<input name="password" type="password" minLength={12} maxLength={128} autoComplete={mode==="login"?"current-password":"new-password"} required/></label>{mode==="register"&&<label className="claim-check"><input name="claim" type="checkbox" defaultChecked/> Rattacher l’historique de cet appareil à mon compte</label>}<button disabled={busy}>{busy?"Veuillez patienter…":mode==="login"?"Se connecter":"Créer mon compte"}</button>{error&&<p role="alert">{error}</p>}</form></section></div>;
}
