"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,RefreshCw,UserRound} from "lucide-react";
import {getLearnerProfile,getProgression} from "@/lib/api";
import type {KnowledgeMasterySummary,LearnerProfile,MasteryState,ProgressionSummary} from "@/lib/types";

const stateLabels:Record<MasteryState,string>={not_enough_data:"Pas assez de données",emerging:"En découverte",practicing:"En consolidation",established:"Bien établi"};
const reasonLabels:Record<string,string>={repeated_negative:"Plusieurs réponses incorrectes récentes",partial_results:"Résultats partiels à consolider",course_gap:"Rappel de cours utile",method_gap:"Méthode encore à consolider",incomplete_work:"Travail récent resté incomplet",prerequisite_gap:"Prérequis immédiat à consolider",inconsistent_results:"Résultats récents encore irréguliers"};
const shortDate=(value:string)=>new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short"}).format(new Date(value));
function Area({item}:{item:KnowledgeMasterySummary}){return <article className={`profile-area ${item.state}`}><header><h3>{item.label}</h3><span>{stateLabels[item.state]}</span></header><p>{item.evidence_count} séance{item.evidence_count>1?"s":""} · difficulté {item.difficulty_min===item.difficulty_max?item.difficulty_min:`${item.difficulty_min}–${item.difficulty_max}`}</p><small>Dernière pratique : {shortDate(item.last_practiced_at)}</small></article>}
export function LearnerProfileView({onClose}:{onClose:()=>void}){
 const[profile,setProfile]=useState<LearnerProfile>();const[progression,setProgression]=useState<ProgressionSummary>();const[state,setState]=useState<"loading"|"ready"|"error">("loading");
 async function load(){setState("loading");try{const[p,next]=await Promise.all([getLearnerProfile(),getProgression()]);setProfile(p);setProgression(next);setState("ready")}catch{setState("error")}}
 useEffect(()=>{let active=true;Promise.all([getLearnerProfile(),getProgression()]).then(([p,next])=>{if(active){setProfile(p);setProgression(next);setState("ready")}}).catch(()=>{if(active)setState("error")});return()=>{active=false}},[]);
 return <section className="profile-view"><header className="profile-title"><button className="history-back" onClick={onClose}><ArrowLeft/> Retour à l’espace de travail</button><h1><UserRound/> Profil d’apprentissage</h1><p>La progression mesure la pratique régulière ; la maîtrise mathématique repose séparément sur les résultats évalués.</p></header>{state==="loading"?<p className="profile-state" aria-live="polite">Chargement du profil…</p>:state==="error"?<div className="profile-state" role="alert">Impossible de charger le profil.<button onClick={()=>void load()}><RefreshCw/> Réessayer</button></div>:profile&&progression&&<ProfileContent profile={profile} progression={progression}/>}</section>
}
function ProfileContent({profile,progression}:{profile:LearnerProfile;progression:ProgressionSummary}){
 const a=profile.activity;const range=progression.next_grade_xp-progression.current_grade_start_xp;const progress=range?Math.max(0,Math.min(100,(progression.total_xp-progression.current_grade_start_xp)/range*100)):0;
 const grouped=profile.knowledge.reduce<Record<string,KnowledgeMasterySummary[]>>((result,node)=>{(result[node.parent_label??"Autres notions"]??=[]).push(node);return result},{});const groups=Object.entries(grouped);
 return <div className="profile-content"><section className="progression-section" aria-labelledby="progression-title"><h2 id="progression-title">Progression</h2><div className="progression-stats"><strong>Grade {progression.grade}</strong><span>{progression.total_xp} XP</span><span>🔥 Série actuelle : {progression.current_streak_days} jour{progression.current_streak_days>1?"s":""}</span><span>Record : {progression.longest_streak_days} jour{progression.longest_streak_days>1?"s":""}</span></div><div className="grade-progress" role="progressbar" aria-label="Progression vers le prochain grade" aria-valuemin={progression.current_grade_start_xp} aria-valuemax={progression.next_grade_xp} aria-valuenow={progression.total_xp}><span style={{width:`${progress}%`}}/></div><p>{progression.xp_to_next_grade} XP avant le grade {progression.grade+1}</p></section><section aria-labelledby="activity-title"><h2 id="activity-title">Activité récente</h2><p className="activity-line"><strong>{a.sessions_total}</strong> séances · <strong>{a.sessions_completed}</strong> terminées · <strong>{a.sessions_abandoned}</strong> abandonnées · <strong>{a.attempts_total}</strong> tentatives</p><p>{a.sessions_last_30_days} séance{a.sessions_last_30_days>1?"s":""} ces 30 derniers jours</p></section><section className="mastery-section" aria-labelledby="mastery-title"><h2 id="mastery-title">Maîtrise mathématique</h2><p>La maîtrise par notion est indépendante des XP, du grade et des séries.</p>{profile.knowledge.length===0?<div className="profile-empty"><h3>Pas encore assez de séances pour établir une maîtrise.</h3><p>Cette synthèse se précisera avec des travaux évalués.</p></div>:groups.map(([domain,nodes])=><section key={domain} className="knowledge-domain"><h3>{domain}</h3><div className="profile-grid">{nodes?.map(x=><Area key={x.identifier} item={x}/>)}</div></section>)}</section>{profile.needs_consolidation.length>0&&<section><h2>À consolider</h2><div className="consolidation-list">{profile.needs_consolidation.map(x=><article key={`${x.kind}-${x.identifier}`}><h3>{x.label}</h3>{x.reasons.map(reason=><p key={reason}>{reasonLabels[reason]??reason}</p>)}{x.prerequisites?.map(prerequisite=><p key={prerequisite.identifier}>{prerequisite.status==="not_practiced"?`${prerequisite.label} n’a pas encore été suffisamment travaillé.`:`${prerequisite.label} à consolider avant ${x.label.toLocaleLowerCase("fr-FR")}.`}</p>)}</article>)}</div></section>}{profile.strengths.length>0&&<section><h2>Points bien établis dans les séances récentes</h2><div className="profile-grid">{profile.strengths.map(x=><Area key={x.identifier} item={x}/>)}</div></section>}</div>
}
