"use client";
import {useEffect,useState} from "react";
import {getProblemResources} from "@/lib/api";
import type {PedagogicalResource,ProblemDetail,ResourceType,SelectionAdaptation} from "@/lib/types";
import {DifficultyBadge} from "./difficulty-badge";
import {TopicBadge} from "./topic-badge";
import {SourceBadge} from "./source-badge";
import {MathContent} from "./math-content";
import {PedagogicalResourceDialog} from "./pedagogical-resource-dialog";

export function CollapsibleProblemPanel({problem,adaptation,expanded:controlledExpanded,onExpandedChange}:{problem:ProblemDetail;adaptation?:SelectionAdaptation;expanded?:boolean;onExpandedChange?:(expanded:boolean)=>void}) {
  const[selected,setSelected]=useState<string>(),[internalExpanded,setInternalExpanded]=useState(true),[loaded,setLoaded]=useState<{problemId:string;resources:PedagogicalResource[]}>();
  const resources=loaded?.problemId===problem.id?loaded.resources:[];
  const expanded=controlledExpanded??internalExpanded;
  function changeExpanded(next:boolean){if(controlledExpanded===undefined)setInternalExpanded(next);onExpandedChange?.(next)}
  useEffect(()=>{let active=true;queueMicrotask(()=>setSelected(undefined));getProblemResources(problem.id).then(value=>{if(active&&value.problem_id===problem.id)setLoaded({problemId:problem.id,resources:value.resources})}).catch(()=>{if(active)setLoaded({problemId:problem.id,resources:[]})});return()=>{active=false}},[problem.id]);
  const first=(type:ResourceType)=>resources.find(resource=>resource.type===type);
  function show(resource:PedagogicalResource){try{const key=`khollelab.resources.${problem.id}`,current=JSON.parse(localStorage.getItem(key)??"{}") as Record<string,number>;current[resource.id]=(current[resource.id]??0)+1;localStorage.setItem(key,JSON.stringify(current))}catch{}setSelected(resource.id)}
  return <section className="panel problem collapsible-problem"><button className="problem-toggle" aria-expanded={expanded} title={expanded?"Replier l’énoncé":"Afficher l’énoncé"} onClick={()=>changeExpanded(!expanded)}><span className="problem-toggle-label"><span aria-hidden="true">{expanded?"▾":"▸"}</span><span>ÉNONCÉ</span></span><strong className="problem-toggle-title">{problem.title}</strong><span className="problem-toggle-summary">Niveau {problem.curriculum.level==="premiere"?"Première":problem.curriculum.level} · Difficulté {problem.curriculum.difficulty} · {problem.topics[0]}{problem.estimatedMinutes?` · ~${problem.estimatedMinutes} min`:""}</span></button>{expanded&&<div className="problem-body">{problem.subtitle&&<p>{problem.subtitle}</p>}<div className="problem-meta"><span className="badge">Niveau : {problem.curriculum.level}</span><DifficultyBadge difficulty={problem.curriculum.difficulty}/>{problem.estimatedMinutes&&<span className="badge">~{problem.estimatedMinutes} min</span>}</div><div className="topics">{problem.topics.map(topic=><TopicBadge key={topic} topic={topic}/>)}</div><SourceBadge source={problem.source} year={problem.year}/>{adaptiveMessage(adaptation)&&<p className="adaptation" role="status">{adaptiveMessage(adaptation)}</p>}<MathContent content={problem.statement}/>{!!problem.prerequisites.length&&<details className="prerequisites"><summary>Prérequis</summary><p>Prérequis conseillés :</p><ul>{problem.prerequisites.map(item=><li key={item}>{item.replaceAll("-"," ")}</li>)}</ul></details>}{resources.length>0&&<div className="resource-actions" aria-label="Ressources pédagogiques">{first("course")&&<button onClick={()=>show(first("course")!)}>📘 Point de cours</button>}{first("example")&&<button onClick={()=>show(first("example")!)}>Exemple guidé</button>}{first("video")&&<button onClick={()=>show(first("video")!)}>▶ Vidéo</button>}</div>}{selected&&<PedagogicalResourceDialog key={selected} resourceId={selected} onClose={()=>setSelected(undefined)}/>}</div>}</section>
}
export const ProblemPanel=CollapsibleProblemPanel;

function adaptiveMessage(adaptation?:SelectionAdaptation):string|undefined{if(!adaptation?.reason_codes.length)return;const topic=adaptation.targeted_topics[0]?.replaceAll("-"," ");const skill=adaptation.targeted_skills[0]?.replaceAll("-"," ");if(adaptation.reason_codes.includes("target_skill")&&skill)return `Proposé pour consolider ${skill}.`;if(adaptation.reason_codes.includes("target_topic")&&topic)return `Choisi pour retravailler ${topic}.`;if(adaptation.reason_codes.includes("topic_diversity"))return "Choisi pour varier les types d’exercices.";if(adaptation.reason_codes.includes("recommended_sequence"))return "Proposé dans la continuité du travail récent.";if(adaptation.reason_codes.includes("recent_problem_avoidance"))return "Choisi pour varier les exercices."}
