"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAttemptStore} from "@/stores/useAttemptStore";
import {ApiError,assessTutor,createEvaluation,getEvaluation,getLatestTutor,getReferenceSolution,retryEvaluation} from "@/lib/api";
import type {Evaluation,EvaluationStage,TutorAssessment,TutorTrigger} from "@/lib/types";
import {MathContent} from "./math-content";

const verdicts:Record<string,string>={correct:"Correct",mostly_correct:"Globalement juste",partial:"Partiellement correct",incorrect:"Raisonnement incorrect",non_answer:"Réponse insuffisante"};
const methods:Record<string,string>={same_strategy:"Même stratégie que le corrigé",similar_strategy:"Stratégie proche du corrigé",alternative_valid_strategy:"Méthode alternative valide",alternative_invalid_strategy:"Méthode alternative non valide",no_meaningful_strategy:"Aucune méthode identifiable"};
const errors:Record<string,string>={REMOTE_TRUNCATED:"L’analyse a dépassé la taille de réponse prévue.",REMOTE_SCHEMA:"La réponse distante ne respecte pas le format mathématique attendu.",REMOTE_TIMEOUT:"Le service d’analyse a mis trop de temps à répondre.",REMOTE_RATE_LIMITED:"Le service d’analyse est temporairement saturé."};
const order:EvaluationStage[]=["queued","candidate_audit","adjudication","finalizing","completed"];

function Progress({stage,progress}:{stage:EvaluationStage;progress:number}){
  const rows:[EvaluationStage,string][]=[["candidate_audit","Analyse du raisonnement"],["adjudication","Comparaison au corrigé"],["finalizing","Synthèse"]];
  const current=order.indexOf(stage);
  return <aside className="professor analysing" aria-live="polite"><div><span>LE PROFESSEUR EXAMINE VOTRE COPIE</span><small>{progress}%</small></div><blockquote><p>✓ Copie enregistrée</p>{rows.map(([key,label])=>{const position=order.indexOf(key);return <p key={key}>{position<current?"✓":position===current?"●":"○"} {label}</p>})}</blockquote></aside>
}

export function ProfessorPanel(){
  const attemptId=useAttemptStore(s=>s.attemptId),status=useAttemptStore(s=>s.status);
  const[e,setE]=useState<Evaluation>();const[queueing,setQueueing]=useState(false);
  const solution=useAttemptStore(s=>s.solution),saveState=useAttemptStore(s=>s.saveState);
  const[tutor,setTutor]=useState<TutorAssessment|null>(null),[tutorState,setTutorState]=useState<"observing"|"waiting"|"thinking"|"silent"|"intervened"|"cooldown"|"unavailable">("observing"),[auto,setAuto]=useState(true);
  const inFlight=useRef(false),lastAssessed=useRef(""),previous=useRef(""),changedAt=useRef(0),startedAt=useRef(0),stalledFor=useRef(""),helpLevel=useRef(1);
  useEffect(()=>{queueMicrotask(()=>setAuto(localStorage.getItem("khollelab.autoTutor")!=="off"))},[]);
  useEffect(()=>{if(status==="draft"&&attemptId)getLatestTutor(attemptId).then(x=>{if(x?.intervention_needed){setTutor(x);setTutorState("intervened")}}).catch(()=>{})},[attemptId,status]);
  useEffect(()=>{const now=Date.now();changedAt.current=now;if(!startedAt.current)startedAt.current=now},[solution]);
  const ask=useCallback(async(trigger:TutorTrigger,level:number)=>{if(!attemptId||inFlight.current)return;const saved=await useAttemptStore.getState().save();if(!saved)return;const snapshot=useAttemptStore.getState();inFlight.current=true;setTutorState("thinking");try{const result=await assessTutor(attemptId,snapshot.revision,trigger,level);const current=useAttemptStore.getState();if(result&&current.revision===result.revision&&current.solution===snapshot.solution){setTutor(result);setTutorState(result.intervention_needed?"intervened":"silent");lastAssessed.current=canonical(current.solution)}}catch(error){if(error instanceof ApiError&&error.status===429)setTutorState("cooldown");else setTutorState("unavailable")}finally{inFlight.current=false}},[attemptId]);
  useEffect(()=>{if(status!=="draft"||!auto||!attemptId)return;const timer=setInterval(()=>{const now=Date.now(),normalized=canonical(solution),old=canonical(previous.current);const meaningful=Math.abs(normalized.length-old.length)>=12||(normalized!==old&&/[=<>+\-*/]/.test(normalized));if(saveState!=="saving"&&normalized&&now-startedAt.current>=45000&&meaningful&&normalized!==lastAssessed.current&&now-changedAt.current>=6000){previous.current=solution;void ask("meaningful_progress",1)}else if(normalized&&now-changedAt.current>=90000&&stalledFor.current!==normalized){stalledFor.current=normalized;void ask("stalled",1)}},1000);return()=>clearInterval(timer)},[status,auto,attemptId,solution,saveState,ask]);
  const refresh=useCallback(async()=>{if(!attemptId)return;try{setE(await getEvaluation(attemptId))}catch(error){if(!(error instanceof ApiError&&error.status===404))throw error}},[attemptId]);
  useEffect(()=>{if(status!=="submitted"||!attemptId)return;queueMicrotask(()=>void refresh())},[status,attemptId,refresh]);
  useEffect(()=>{if(!attemptId||e?.status!=="running")return;const started=Date.now();let timer:ReturnType<typeof setTimeout>,cancelled=false;const poll=async()=>{try{const next=await getEvaluation(attemptId);if(cancelled)return;setE(next);if(next.status==="running")timer=setTimeout(()=>void poll(),Date.now()-started<15_000?2000:3500)}catch{if(!cancelled)timer=setTimeout(()=>void poll(),3500)}};timer=setTimeout(()=>void poll(),2000);return()=>{cancelled=true;clearTimeout(timer)}},[attemptId,e?.status]);
  async function run(retry=false){if(!attemptId||queueing)return;setQueueing(true);try{setE(await(retry?retryEvaluation(attemptId):createEvaluation(attemptId)))}catch{setE({status:"failed",stage:"failed",progress:100,max_score:20,strengths:[],issues:[],missing_justifications:[]})}finally{setQueueing(false)}}
  if(status!=="submitted")return <aside className="professor" aria-live="polite"><div><span>PROFESSEUR</span><small>{!auto?"En retrait":tutorState==="thinking"?"◐ Réfléchit à votre dernière étape…":tutorState==="unavailable"?"Indisponible":tutorState==="cooldown"?"En attente":"● Observe"}</small></div>{tutor?.intervention_needed&&tutor.intervention&&<blockquote>« {tutor.intervention} »</blockquote>}{tutorState==="unavailable"&&<blockquote>Professeur temporairement indisponible.</blockquote>}<div className="tutor-actions"><button type="button" onClick={()=>{helpLevel.current=Math.min(5,Math.max(2,helpLevel.current+1));void ask("ask_hint",helpLevel.current)}}>Un indice</button><button type="button" onClick={()=>{helpLevel.current=Math.min(5,Math.max(3,helpLevel.current+1));void ask("i_am_stuck",helpLevel.current)}}>Je suis bloqué</button><button type="button" aria-pressed={!auto} onClick={()=>{const next=!auto;setAuto(next);localStorage.setItem("khollelab.autoTutor",next?"on":"off")}}>{auto?"Silence":"Réactiver le colleur auto"}</button></div></aside>;
  if(!attemptId)return <aside className="professor"><div><span>PROFESSEUR</span></div><blockquote>Impossible d’identifier la tentative présentée.</blockquote></aside>;
  if(queueing)return <Progress stage="queued" progress={5}/>;
  if(!e)return <aside className="professor"><div><span>PROFESSEUR</span><small>Votre copie est prête à être examinée.</small></div><blockquote><button className="examine" onClick={()=>void run()}>Examiner ma copie</button></blockquote></aside>;
  if(e.status==="running")return <Progress stage={e.stage} progress={e.progress}/>;
  if(e.status==="failed")return <aside className="evaluation failure"><h2>{errors[e.error_code||""]||"L’analyse n’a pas pu être terminée."}</h2><p>Code : {e.error_code||"REMOTE_PROVIDER"}</p><p>Votre copie est enregistrée et n’a pas été perdue.</p><button className="examine" onClick={()=>void run(true)}>Réessayer</button> <button className="examine" onClick={()=>window.dispatchEvent(new CustomEvent("khollelab:open-diagnostics"))}>Voir les logs</button></aside>;
  return <EvaluationPanel value={e} attemptId={attemptId}/>;
}
function canonical(value:string){return value.replace(/\s+/g,"").normalize("NFKC")}
export function EvaluationPanel({value:v,attemptId}:{value:Evaluation;attemptId:string}){const[open,setOpen]=useState(true),[correction,setCorrection]=useState<string>(),[correctionError,setCorrectionError]=useState(false);const r=v.rubric;async function showCorrection(){if(correction){setCorrection(undefined);return}setCorrectionError(false);try{setCorrection((await getReferenceSolution(attemptId)).reference_solution)}catch{setCorrectionError(true)}}const model=(v.model||"modèle").split(":")[0].split("/").pop();const provenance=v.provider==="fake"?"Évaluation simulée":`${model} · ${v.inference_backend||"auto"}${v.elapsed_ms?` · Analyse distante · ${Math.round(v.elapsed_ms/1000)} s`:""}`;return <section id="debrief" className={`evaluation ${open?"open":"collapsed"}`}><button className="debrief-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><span>{open?"▾":"▸"} DÉBRIEF DE COLLE</span><b>{v.score}/20 · {verdicts[v.verdict||""]}</b></button>{open&&<div className="debrief-content"><p className="evaluation-provider">{provenance}</p>{v.confidence!==undefined&&v.confidence<.65&&<p className="caution">Évaluation à interpréter avec prudence.</p>}{r&&<div className="rubric"><span>Exactitude <b>{r.mathematical_correctness} / 10</b></span><span>Rigueur <b>{r.rigor} / 5</b></span><span>Clarté <b>{r.clarity} / 2</b></span><span>Efficacité <b>{r.efficiency} / 3</b></span></div>}<div className="debrief-grid"><div><h3>✓ POINTS SOLIDES</h3>{v.strengths.map(x=><p key={x}>{x}</p>)}</div><div><h3>⚠ À CORRIGER</h3>{v.issues.map((x,i)=><p key={i}>{x.description}</p>)}{v.missing_justifications.map(x=><p key={x}>{x}</p>)}</div></div><div className="method"><h3>MÉTHODE</h3><b>{methods[v.reference_relationship||""]}</b><p>{v.strategy_summary}</p><small>Comparaison au corrigé : {v.reference_method_summary}</small><br/><button className="correction-toggle" onClick={()=>void showCorrection()}>{correction?"Masquer":"📖 Voir le corrigé complet"}</button>{correction&&<div className="reference-solution"><h3>CORRIGÉ DE RÉFÉRENCE</h3><MathContent content={correction}/></div>}{correctionError&&<p role="alert">Le corrigé n’est pas disponible pour le moment.</p>}</div><div className="feedback"><h3>CONSEIL DU PROFESSEUR</h3><p>{v.key_feedback}</p><p>{v.suggested_improvement}</p></div></div>}</section>}
