"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,History,RefreshCw} from "lucide-react";
import {getSession,getSessions} from "@/lib/api";
import type {LearningSessionDetail,LearningSessionSummary} from "@/lib/types";
import {MathContent} from "./math-content";
const statuses={active:"En cours",completed:"Terminée",abandoned:"Abandonnée"};
const date=(value:string)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const duration=(seconds:number)=>seconds?`${Math.floor(seconds/60)} min`:"—";
export function SessionHistory({onClose,onResume}:{onClose:()=>void;onResume:(session:LearningSessionDetail)=>void}){
 const[items,setItems]=useState<LearningSessionSummary[]>([]),[detail,setDetail]=useState<LearningSessionDetail>(),[detailId,setDetailId]=useState<string>();
 const[state,setState]=useState<"loading"|"ready"|"error">("loading"),[detailState,setDetailState]=useState<"detail_loading"|"detail_ready"|"detail_error">("detail_ready");
 async function load(){setState("loading");try{setItems(await getSessions());setState("ready")}catch{setState("error")}}
 async function loadDetail(id:string){setDetailId(id);setDetail(undefined);setDetailState("detail_loading");try{setDetail(await getSession(id));setDetailState("detail_ready")}catch{setDetailState("detail_error")}}
 useEffect(()=>{getSessions().then(values=>{setItems(values);setState("ready")}).catch(()=>setState("error"))},[]);
 function back(){setDetail(undefined);setDetailId(undefined);setDetailState("detail_ready")}
 if(detailState!=="detail_ready"||detail)return <section className="history-view"><button className="history-back" onClick={back}><ArrowLeft/> Retour à l’historique</button>{detailState==="detail_loading"?<p className="history-state">Chargement de la séance…</p>:detailState==="detail_error"?<div className="history-state" role="alert">Impossible de charger cette séance.<button onClick={()=>detailId&&void loadDetail(detailId)}><RefreshCw/> Réessayer</button></div>:detail&&<article className="history-detail"><header><div><span className={`session-status ${detail.status}`}>{statuses[detail.status]}</span><h1>{detail.problem_title}</h1></div>{detail.status==="active"&&<button className="resume" onClick={()=>onResume(detail)}>Reprendre</button>}</header><dl><div><dt>Début</dt><dd>{date(detail.started_at)}</dd></div><div><dt>Dernière activité</dt><dd>{date(detail.updated_at)}</dd></div><div><dt>Durée</dt><dd>{duration(detail.duration_seconds)}</dd></div><div><dt>Tentatives</dt><dd>{detail.number_of_attempts}</dd></div></dl>{detail.problem&&<section><h2>Énoncé original</h2><MathContent content={String(detail.problem.statement??"")}/></section>}<section><h2>Dernière copie</h2>{detail.final_work?<MathContent content={detail.final_work}/>:<p>Aucun travail écrit.</p>}</section>{detail.tutor_assessment&&<section><h2>Retour du professeur</h2><p>{detail.tutor_assessment.intervention??detail.tutor_assessment.student_state}</p></section>}{detail.resource_recommendation&&<section><h2>Ressource recommandée</h2><p>{detail.resource_recommendation.title}</p></section>}</article>}</section>;
 return <section className="history-view"><header className="history-title"><button className="history-back" onClick={onClose}><ArrowLeft/> Retour à l’espace de travail</button><h1><History/> Historique des séances</h1></header>{state==="loading"?<p className="history-state">Chargement de l’historique…</p>:state==="error"?<div className="history-state" role="alert">Impossible de charger l’historique.<button onClick={()=>void load()}><RefreshCw/> Réessayer</button></div>:items.length===0?<p className="history-state">Aucune séance enregistrée pour le moment.</p>:<div className="history-list">{items.map(item=><button key={item.session_id} className="history-row" onClick={()=>void loadDetail(item.session_id)}><span><strong>{item.problem_title}</strong><small>{date(item.completed_at??item.updated_at)}</small></span><span>{item.number_of_attempts} tentative{item.number_of_attempts>1?"s":""}</span><span>{duration(item.duration_seconds)}</span><span className={`session-status ${item.status}`}>{statuses[item.status]}</span></button>)}</div>}</section>
}
