"use client";
import {Mic,Square} from "lucide-react";
import {useEffect,useRef,useState,useSyncExternalStore} from "react";
import {createSpeechRecognition,normalizeDictation,speechRecognitionSupported,type BrowserSpeechRecognition} from "@/lib/speech-recognition";
type DictationState="idle"|"listening"|"processing";
const errors:Record<string,string>={"not-allowed":"Accès au microphone refusé. Vous pouvez continuer avec les claviers.","service-not-allowed":"Reconnaissance vocale indisponible.","audio-capture":"Aucun microphone disponible.","no-speech":"Aucune parole détectée.",network:"Service de reconnaissance vocale indisponible.",aborted:"Dictée arrêtée."};
export function SpeechDictationControl({onFinal,disabled=false,contextKey}:{onFinal:(text:string)=>void;disabled?:boolean;contextKey?:string}){
 const supported=useSyncExternalStore(()=>()=>{},speechRecognitionSupported,()=>false),recognition=useRef<BrowserSpeechRecognition|null>(null),generation=useRef(0),[state,setState]=useState<DictationState>("idle"),[status,setStatus]=useState(""),[interim,setInterim]=useState("");
 // A context transition must synchronously invalidate callbacks before the old recognizer can emit again.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{generation.current++;const active=recognition.current;recognition.current=null;active?.abort();setState("idle");setInterim("")},[contextKey,disabled]);
 useEffect(()=>()=>{generation.current++;recognition.current?.abort();recognition.current=null},[]);
 function begin(){if(disabled||!supported)return;if(state==="listening"){setState("processing");setStatus("Transcription…");recognition.current?.stop();return}if(state!=="idle")return;const next=createSpeechRecognition();if(!next){setStatus("Dictée vocale indisponible sur ce navigateur.");return}const current=++generation.current;recognition.current=next;setStatus("Activation du microphone…");setInterim("");next.onstart=()=>{if(current===generation.current){setState("listening");setStatus("Écoute en cours.")}};next.onresult=event=>{if(current!==generation.current)return;let temporary="";for(let index=event.resultIndex;index<event.results.length;index++){const result=event.results[index],text=normalizeDictation(result[0]?.transcript??"");if(!text)continue;if(result.isFinal)onFinal(text);else temporary=[temporary,text].filter(Boolean).join(" ")}setInterim(temporary);if(!temporary)setStatus("Transcription…")};next.onerror=event=>{if(current!==generation.current)return;setStatus(errors[event.error]??"La dictée vocale n’a pas pu démarrer.");setInterim("")};next.onend=()=>{if(current!==generation.current)return;recognition.current=null;setState("idle");setInterim("");setStatus(previous=>previous==="Transcription…"?"Dictée insérée.":previous)};next.start()}
 if(!supported)return <p className="speech-unavailable" role="status">Dictée vocale indisponible sur ce navigateur.</p>;
 const listening=state==="listening";return <div className="speech-control"><button type="button" className={listening?"listening":""} disabled={disabled} aria-label={listening?"Arrêter la dictée":"Dicter mon raisonnement"} aria-pressed={listening} onClick={begin}>{listening?<Square aria-hidden="true"/>:<Mic aria-hidden="true"/>}<span>{listening?"Écoute…":state==="processing"?"Transcription…":"Dicter"}</span></button><span className="speech-status" aria-live="polite">{interim||status}</span></div>
}
