import {render,screen,waitFor,cleanup,fireEvent} from "@testing-library/react";import {afterEach,beforeEach,expect,it,vi} from "vitest";import Home from "./page";import * as api from "@/lib/api";
vi.mock("@/lib/api");const metadata={levels:[{id:"seconde",label:"Seconde"},{id:"premiere",label:"Première"},{id:"terminale",label:"Terminale"},{id:"maths-sup",label:"Maths Sup"},{id:"maths-spe",label:"Maths Spé"}],difficulties:["Découverte","Standard","Approfondissement","Difficile","Challenge"].map((label,index)=>({id:index+1,label}))};const summary={id:"demo",title:"Démo",curriculum:{level:"seconde",difficulty:2},topics:["algebra"],source:{type:"internal",name:"Test"}};const detail={...summary,statement:"Énoncé",hintLevels:[],prerequisites:[],skills:[]};
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();vi.mocked(api.getHealth).mockResolvedValue({status:"ok",database:"ok",problem_corpus:"ok",problem_count:50,resource_corpus:"ok",resource_count:15,curriculum_levels:5});vi.mocked(api.getCurriculum).mockResolvedValue(metadata);vi.mocked(api.getProblemResources).mockResolvedValue({problem_id:"demo",resources:[]});vi.mocked(api.getActiveSession).mockResolvedValue(null)});afterEach(cleanup);
it("shows an empty selection state",async()=>{vi.mocked(api.getProblems).mockResolvedValue([]);vi.mocked(api.selectProblem).mockResolvedValue({problem:null,requested_level:"seconde",requested_difficulty:2,fallback_used:false});render(<Home/>);expect(await screen.findByText("Aucun exercice ne correspond à ces critères.")).toBeInTheDocument()});
it("shows a controlled API error",async()=>{vi.mocked(api.getProblems).mockRejectedValue(new Error("down"));render(<Home/>);expect(await screen.findByText("Le corpus d’exercices est indisponible.")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Réessayer"})).toBeInTheDocument()});
it("shows all curricula and loads a selected problem",async()=>{vi.mocked(api.getProblems).mockResolvedValue([summary]);vi.mocked(api.selectProblem).mockResolvedValue({problem:detail,requested_level:"seconde",requested_difficulty:2,actual_difficulty:2,fallback_used:false});render(<Home/>);await waitFor(()=>expect(screen.getByText("Démo")).toBeInTheDocument());for(const item of metadata.levels)expect(screen.getByRole("button",{name:item.label})).toBeInTheDocument();for(const item of metadata.difficulties)expect(screen.getByRole("button",{name:`${item.id} ${item.label}`})).toBeInTheDocument();expect(api.selectProblem).toHaveBeenCalledWith("seconde",2,undefined,"manual")})

it("uses adaptive intent only for Autre exercice and renders its explanation",async()=>{vi.mocked(api.getProblems).mockResolvedValue([summary]);vi.mocked(api.selectProblem).mockResolvedValue({problem:detail,requested_level:"seconde",requested_difficulty:2,actual_difficulty:2,fallback_used:false,selection_mode:"adaptive",adaptation:{reason_codes:["target_skill"],targeted_topics:[],targeted_skills:["induction"],targeted_prerequisites:[]}});render(<Home/>);await screen.findByText("Démo");fireEvent.click(screen.getByRole("button",{name:"Choisir un autre exercice"}));await waitFor(()=>expect(api.selectProblem).toHaveBeenLastCalledWith("seconde",2,undefined,"adaptive"));expect(await screen.findByText("Proposé pour consolider induction.")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Première"}));await waitFor(()=>expect(api.selectProblem).toHaveBeenLastCalledWith("premiere",2,undefined,"manual"))})
it("shows unavailable remote inference without blocking the workspace",async()=>{vi.mocked(api.getInferenceStatus).mockResolvedValue({provider:"huggingface",status:"unavailable",family:"qwen",fast_model:"Qwen3-8B",fast_backend:"nscale",deep_model:"Qwen3-32B",deep_backend:"nscale"});vi.mocked(api.getProblems).mockResolvedValue([summary]);vi.mocked(api.selectProblem).mockResolvedValue({problem:detail,requested_level:"seconde",requested_difficulty:2,actual_difficulty:2,fallback_used:false});render(<Home/>);expect(await screen.findByText("IA ⚠ indisponible")).toBeInTheDocument();expect(await screen.findByText("Démo")).toBeInTheDocument()})
it("shows ready remote inference",async()=>{vi.mocked(api.getInferenceStatus).mockResolvedValue({provider:"huggingface",status:"ready",family:"qwen",fast_model:"Qwen3-8B",fast_backend:"nscale",deep_model:"Qwen3-32B",deep_backend:"nscale"});vi.mocked(api.getProblems).mockResolvedValue([]);vi.mocked(api.selectProblem).mockResolvedValue({problem:null,requested_level:"seconde",requested_difficulty:2,fallback_used:false});render(<Home/>);expect(await screen.findByText("IA ● prête")).toBeInTheDocument()})

it("renders the canonical brand lockup without duplicate textual branding",()=>{vi.mocked(api.getProblems).mockResolvedValue([]);vi.mocked(api.selectProblem).mockResolvedValue({problem:null,requested_level:"seconde",requested_difficulty:2,fallback_used:false});render(<Home/>);const brand=screen.getByRole("img",{name:"KHOLLELAB"});expect(brand).toHaveAttribute("src",expect.stringContaining("khollelab-logo-dark.svg"));expect(screen.getAllByRole("img",{name:"KHOLLELAB"})).toHaveLength(1)});
it("reopens the statement when a genuinely new problem is selected",async()=>{const next={...detail,id:"demo-next",title:"Nouvel exercice",statement:"Nouvel énoncé"};vi.mocked(api.getProblems).mockResolvedValue([summary,{...summary,id:"demo-next",title:"Nouvel exercice"}]);vi.mocked(api.selectProblem).mockResolvedValueOnce({problem:detail,requested_level:"seconde",requested_difficulty:2,actual_difficulty:2,fallback_used:false}).mockResolvedValueOnce({problem:next,requested_level:"seconde",requested_difficulty:2,actual_difficulty:2,fallback_used:false});render(<Home/>);const toggle=await screen.findByRole("button",{name:/ÉNONCÉ/});fireEvent.click(toggle);expect(toggle).toHaveAttribute("aria-expanded","false");fireEvent.click(screen.getByRole("button",{name:"Choisir un autre exercice"}));expect(await screen.findByText("Nouvel exercice")).toBeInTheDocument();await waitFor(()=>expect(screen.getByRole("button",{name:/ÉNONCÉ/})).toHaveAttribute("aria-expanded","true"))})
