import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {SessionHistory} from "../session-history";
import * as api from "@/lib/api";
vi.mock("@/lib/api",()=>({getSessions:vi.fn(),getSession:vi.fn()}));
const summary={session_id:"s1",problem_id:"p1",problem_title:"Suites et limites",status:"active" as const,created_at:"2026-09-06T08:00:00Z",updated_at:"2026-09-06T08:05:00Z",started_at:"2026-09-06T08:00:00Z",completed_at:null,duration_seconds:300,number_of_attempts:1,number_of_tutor_interactions:0,outcome:null};
afterEach(cleanup);
describe("SessionHistory",()=>{beforeEach(()=>vi.clearAllMocks());it("renders the deliberate empty state",async()=>{vi.mocked(api.getSessions).mockResolvedValue([]);render(<SessionHistory onClose={vi.fn()} onResume={vi.fn()}/>);expect(await screen.findByText("Aucune séance enregistrée pour le moment.")).toBeInTheDocument()});it("renders statuses, read-only detail, resume and workspace navigation",async()=>{const resume=vi.fn(),close=vi.fn();vi.mocked(api.getSessions).mockResolvedValue([summary]);vi.mocked(api.getSession).mockResolvedValue({...summary,problem:null,attempts:[],current_attempt_id:null,final_work:"Ma démonstration",tutor_assessment:null,resource_recommendation:null});render(<SessionHistory onClose={close} onResume={resume}/>);expect(await screen.findByText("En cours")).toBeInTheDocument();fireEvent.click(screen.getByText("Suites et limites"));expect(await screen.findByText("Ma démonstration")).toBeInTheDocument();fireEvent.click(screen.getByText("Reprendre"));expect(resume).toHaveBeenCalledWith(expect.objectContaining({session_id:"s1",problem_id:"p1"}));expect(api.getSession).toHaveBeenCalledTimes(1);expect(api.getSessions).toHaveBeenCalledTimes(1);expect(screen.queryByRole("textbox")).not.toBeInTheDocument()});it("navigates back to the workspace",async()=>{const close=vi.fn();vi.mocked(api.getSessions).mockResolvedValue([]);render(<SessionHistory onClose={close} onResume={vi.fn()}/>);await waitFor(()=>expect(api.getSessions).toHaveBeenCalled());fireEvent.click(screen.getAllByText("Retour à l’espace de travail").at(-1)!);expect(close).toHaveBeenCalled()})});
it("renders wrapped unified and legacy markdown copies without editor markup",async()=>{vi.mocked(api.getSessions).mockResolvedValue([summary]);vi.mocked(api.getSession).mockResolvedValue({...summary,problem:null,attempts:[],current_attempt_id:null,final_work:"\\displaylines{\\text{Je calcule}\\\\ x=2}",tutor_assessment:null,resource_recommendation:null});const{container}=render(<SessionHistory onClose={vi.fn()} onResume={vi.fn()}/>);fireEvent.click(await screen.findByText("Suites et limites"));expect((await screen.findAllByText("Je calcule")).length).toBeGreaterThan(0);expect(container.textContent).not.toContain("\\displaylines");fireEvent.click(screen.getByText("Retour à l’historique"));vi.mocked(api.getSession).mockResolvedValue({...summary,problem:null,attempts:[],current_attempt_id:null,final_work:"Une preuve avec $x=2$.",tutor_assessment:null,resource_recommendation:null});fireEvent.click(screen.getByText("Suites et limites"));expect(await screen.findByText(/Une preuve avec/)).toBeInTheDocument();expect(container.querySelector(".katex")).toBeInTheDocument()});
