import type {CurriculumMetadata,CurriculumProgressHistory,CurriculumProgressSummary} from "@/lib/types";
import {ProgressSparkline} from "./progress-sparkline";
import {LevelUnlockCard} from "./level-unlock-card";
const label=(id:string|null,metadata?:CurriculumMetadata,short=false)=>metadata?.levels.find(level=>level.id===id)?.[short?"short_label":"label"]??"niveau suivant";
export function PostExerciseProgress({before,after,history,historyFailed,newlyUnlocked,busy,error,metadata,onNext,onAdvance}:{before?:CurriculumProgressSummary;after?:CurriculumProgressSummary;history?:CurriculumProgressHistory;historyFailed?:boolean;newlyUnlocked:boolean;busy:boolean;error?:string;metadata?:CurriculumMetadata;onNext:()=>void;onAdvance:()=>void}){
 if(!after)return <section className="post-progress" aria-labelledby="post-progress-title"><h2 id="post-progress-title">Progression momentanément indisponible.</h2><p>Le débrief reste disponible.</p><button onClick={onNext}>Exercice suivant</button></section>;
 const delta=before?.current_level===after.current_level?after.current.solved-before.current.solved:0;
 const current=label(after.current_level,metadata,true),currentLong=label(after.current_level,metadata),next=label(after.next_level,metadata,true);
 return <section className="post-progress" aria-labelledby="post-progress-title"><p className="eyebrow">Progression — {current}</p><h2 id="post-progress-title">{after.current.solved} exercices validés sur {after.current.eligible}</h2><div className="progress-line"><div className="progress-track" role="progressbar" aria-label={`${after.current.solved} exercices validés sur ${after.current.eligible}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={after.current.progress_percent}><span style={{width:`${Math.min(100,after.current.progress_percent)}%`}}/></div><strong>{Math.round(after.current.progress_percent)} %</strong></div>{delta>0?<p className="progress-delta">+{delta} depuis cette khôlle</p>:<><p className="progress-delta">Acquis consolidé</p><p>Ta progression de niveau reste inchangée pour cet exercice. Le professeur utilise néanmoins ce travail pour adapter les prochains exercices.</p></>}<ProgressSparkline history={historyFailed?undefined:history} currentSolved={after.current.solved} currentPercent={after.current.progress_percent}/>{after.next_level&&!after.next_level_unlocked&&<p>Encore <strong>{after.remaining_to_unlock}</strong> pour débloquer la {next}</p>}{newlyUnlocked&&after.next_level?<LevelUnlockCard nextLabel={next} currentLabel={currentLong} busy={busy} error={error} onAdvance={onAdvance} onConsolidate={onNext}/>:<><div className="progress-actions"><button onClick={onNext}>Exercice suivant</button></div>{error&&<p role="alert" className="progress-error">{error}</p>}</>}</section>
}
