import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,expect,it,vi} from "vitest";
import {PostExerciseProgress} from "./post-exercise-progress";
afterEach(cleanup);
const summary=(solved:number)=>({initial_level:"quatrieme",current_level:"quatrieme",highest_unlocked_level:"quatrieme",onboarding_completed:true,unlock_ratio:.6,current:{level:"quatrieme",eligible:19,solved,progress:solved/19,progress_percent:solved/19*100},next_level:"troisieme",next_level_unlocked:false,can_advance:false,remaining_to_unlock:12-solved,levels:[]});
const metadata={academic_year:"2026",levels:[{id:"quatrieme",label:"Quatrième",short_label:"4e",stage:"Collège",programme:{id:"p",label:"P"},domains:[]},{id:"troisieme",label:"Troisième",short_label:"3e",stage:"Collège",programme:{id:"p",label:"P"},domains:[]}],difficulties:[]};
it("shows authoritative post-exercise delta and remaining count",()=>{render(<PostExerciseProgress before={summary(4)} after={summary(5)} newlyUnlocked={false} busy={false} metadata={metadata} onNext={vi.fn()} onAdvance={vi.fn()}/>);expect(screen.getByText("+1 depuis cette khôlle")).toBeInTheDocument();expect(screen.getByText("26 %")).toBeInTheDocument();expect(screen.getByText("7")).toBeInTheDocument()});
it("describes unchanged progress as consolidation without claiming +1",()=>{render(<PostExerciseProgress before={summary(5)} after={summary(5)} newlyUnlocked={false} busy={false} metadata={metadata} onNext={vi.fn()} onAdvance={vi.fn()}/>);expect(screen.getByText("Acquis consolidé")).toBeInTheDocument();expect(screen.queryByText(/\+1/)).not.toBeInTheDocument();expect(screen.getByText(/reste inchangée/)).toBeInTheDocument()});
it("keeps continuation available when progress is unavailable",()=>{const next=vi.fn();render(<PostExerciseProgress newlyUnlocked={false} busy={false} onNext={next} onAdvance={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Exercice suivant"}));expect(next).toHaveBeenCalledOnce()});
