import {act,render,waitFor} from "@testing-library/react";
import {createRef} from "react";
import {expect,it,vi} from "vitest";
import {UnifiedBlackboard,type UnifiedBlackboardHandle} from "./UnifiedBlackboard";
const keyboard=Object.assign(new EventTarget(),{visible:false,layouts:[] as unknown[],alphabeticLayout:"",show:vi.fn(),hide:vi.fn(),setKeycap:vi.fn()});
vi.mock("mathlive",()=>{Object.assign(window,{mathVirtualKeyboard:keyboard});if(!customElements.get("math-field"))customElements.define("math-field",class extends HTMLElement{value="";readOnly=false;defaultMode="text";smartMode=true;smartFence=true;letterShapeStyle="french";mathVirtualKeyboardPolicy="manual";placeholder="";insert=vi.fn((latex:string)=>{this.value+=latex;this.dispatchEvent(new Event("input"))})});return {}});

it("renders exactly one continuous editable field and no block controls",async()=>{const {container}=render(<UnifiedBlackboard solution="" onChange={vi.fn()}/>);await waitFor(()=>expect(container.querySelectorAll("math-field")).toHaveLength(1));expect(container.querySelectorAll("textarea")).toHaveLength(0);expect(container.textContent).not.toMatch(/\+ Texte|\+ Équation/)});
it("uses the one global virtual keyboard and keeps focus",async()=>{const ref=createRef<UnifiedBlackboardHandle>();const {container}=render(<UnifiedBlackboard ref={ref} solution="" onChange={vi.fn()}/>);await waitFor(()=>expect(container.querySelector("math-field")).toBeTruthy());const field=container.querySelector("math-field")!;const focus=vi.spyOn(field as HTMLElement,"focus");const show=vi.spyOn(window.mathVirtualKeyboard,"show");act(()=>ref.current?.toggleKeyboard());expect(show).toHaveBeenCalledOnce();expect(focus).toHaveBeenCalledOnce()});
it("inserts the canonical line break at the current selection and propagates the edit",async()=>{const ref=createRef<UnifiedBlackboardHandle>(),onChange=vi.fn();const {container}=render(<UnifiedBlackboard ref={ref} solution="abcDEF" onChange={onChange}/>);await waitFor(()=>expect(container.querySelector("math-field")).toBeTruthy());const field=container.querySelector("math-field") as HTMLElement&{insert:ReturnType<typeof vi.fn>};act(()=>ref.current?.insertLineBreak());expect(field.insert).toHaveBeenCalledWith("\\\\ ",{insertionMode:"replaceSelection",selectionMode:"after"});expect(onChange).toHaveBeenLastCalledWith(expect.stringContaining("\\\\ "))});
it("exposes the same line-break action on both virtual keyboards",async()=>{render(<UnifiedBlackboard solution="" onChange={vi.fn()}/>);await waitFor(()=>expect(keyboard.setKeycap).toHaveBeenCalled());expect(keyboard.setKeycap).toHaveBeenCalledWith("[return]",expect.objectContaining({label:"↵",insert:"\\\\ ",class:"action"}));const basic=keyboard.layouts[0] as {rows:unknown[][]};expect(basic.rows.flat()).toContainEqual(expect.objectContaining({label:"↵",insert:"\\\\ "}))});
it("turns unmodified physical Enter into a line break but leaves modified Enter alone",async()=>{const {container}=render(<UnifiedBlackboard solution="" onChange={vi.fn()}/>);await waitFor(()=>expect(container.querySelector("math-field")).toBeTruthy());const field=container.querySelector("math-field") as HTMLElement&{insert:ReturnType<typeof vi.fn>};const enter=new KeyboardEvent("keydown",{key:"Enter",cancelable:true});field.dispatchEvent(enter);expect(enter.defaultPrevented).toBe(true);expect(field.insert).toHaveBeenCalledOnce();field.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",ctrlKey:true,cancelable:true}));expect(field.insert).toHaveBeenCalledOnce()});
it("does not insert a line break when read-only",async()=>{const ref=createRef<UnifiedBlackboardHandle>();const {container}=render(<UnifiedBlackboard ref={ref} solution="abc" onChange={vi.fn()} readOnly/>);await waitFor(()=>expect(container.querySelector("math-field")).toBeTruthy());const field=container.querySelector("math-field") as HTMLElement&{insert:ReturnType<typeof vi.fn>};act(()=>ref.current?.insertLineBreak());expect(field.insert).not.toHaveBeenCalled()});
