"use client";
import {useState} from "react";
import Link from "next/link";
import {advanceCurriculumLevel,ApiError} from "@/lib/api";
import type {CurriculumMetadata,CurriculumProgressSummary} from "@/lib/types";
const levelName=(id:string|null,metadata:CurriculumMetadata|undefined,short=false)=>metadata?.levels.find(level=>level.id===id)?.[short?"short_label":"label"]??"Niveau indisponible";
export function CurriculumProgressCard({progress,metadata,active=false,onAdvanced}:{progress:CurriculumProgressSummary;metadata?:CurriculumMetadata;active?:boolean;onAdvanced?:()=>void}){
 const[busy,setBusy]=useState(false),[message,setMessage]=useState("");const percent=Math.max(0,Math.min(100,progress.current.progress_percent));const next=progress.next_level?levelName(progress.next_level,metadata):null;
 async function advance(){setBusy(true);setMessage("");try{await advanceCurriculumLevel();onAdvanced?.()}catch(error){const code=error instanceof ApiError?(error.payload?.detail??error.payload?.error):undefined;setMessage(code==="active_session_exists"?"Une khôlle est en cours. Termine-la avant de changer de niveau.":"Impossible de changer de niveau pour le moment.")}finally{setBusy(false)}}
 return <section className="curriculum-card" aria-labelledby="curriculum-title"><div><p className="eyebrow">Niveau actuel</p><h1 id="curriculum-title"><span className="level-short">{levelName(progress.current_level,metadata,true)}</span><span>{levelName(progress.current_level,metadata)}</span></h1></div><div className="curriculum-measure"><p><strong>{progress.current.solved}</strong> exercices réussis sur <strong>{progress.current.eligible}</strong></p><div className="progress-line"><div className="progress-track" role="progressbar" aria-label={`Progression au niveau ${levelName(progress.current_level,metadata)}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:`${percent}%`}}/></div><strong>{percent} %</strong></div></div>{next&&<div className="next-level"><span>Niveau suivant : <strong>{next}</strong></span>{progress.can_advance?<div className="landing-advance"><strong className="unlocked">Niveau débloqué</strong><button disabled={busy} onClick={()=>void advance()} aria-label={`Passer au niveau ${next}`}>{busy?"Changement…":`Passer en ${levelName(progress.next_level,metadata,true)}`}</button>{active&&<Link href="/kholle">Reprendre ma khôlle</Link>}</div>:progress.next_level_unlocked?<strong className="unlocked">Niveau débloqué</strong>:<span>Encore <strong>{progress.remaining_to_unlock}</strong> exercice{progress.remaining_to_unlock>1?"s":""} réussi{progress.remaining_to_unlock>1?"s":""} pour le débloquer</span>}</div>}{message&&<p className="progress-error" role="alert">{message}</p>}</section>
}
export function CurriculumProgressSkeleton(){return <section className="curriculum-card curriculum-skeleton" aria-label="Chargement de la progression"><span/><span/><span/></section>}
