import type { ProblemDetail, ProblemSource, ProblemSummary } from "./types";
type WireSummary={id:string;title:string;subtitle?:string;level:string;difficulty:number;estimated_minutes?:number;year?:number;topics:string[];source:ProblemSource};type WireDetail=WireSummary&{statement:string;hint_levels:number[]};const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL??"/api";async function request<T>(path:string):Promise<T>{const response=await fetch(`${API_BASE}${path}`,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`API request failed (${response.status})`);return response.json() as Promise<T>}function summary(value:WireSummary):ProblemSummary{return{id:value.id,title:value.title,subtitle:value.subtitle,level:value.level,difficulty:value.difficulty,estimatedMinutes:value.estimated_minutes,year:value.year,topics:value.topics,source:value.source}}export async function getProblems(){return(await request<WireSummary[]>("/problems")).map(summary)}export async function getProblem(id:string):Promise<ProblemDetail>{const value=await request<WireDetail>(`/problems/${encodeURIComponent(id)}`);return{...summary(value),statement:value.statement,hintLevels:value.hint_levels}}

import type { Attempt } from "./types";
export class ApiError extends Error { constructor(public status:number, public payload?:{error?:string;current_revision?:number}){super(payload?.error??`API request failed (${status})`)} }
async function attemptRequest(path:string,init?:RequestInit):Promise<Attempt>{const response=await fetch(`${API_BASE}${path}`,{...init,headers:{Accept:"application/json","Content-Type":"application/json",...init?.headers}});const data=await response.json();if(!response.ok)throw new ApiError(response.status,data);return data}
export const createAttempt=(problemId:string)=>attemptRequest("/attempts",{method:"POST",body:JSON.stringify({problem_id:problemId})});
export const getAttempt=(id:string)=>attemptRequest(`/attempts/${id}`);
export const patchAttempt=(id:string,solution:string,elapsed:number,revision:number)=>attemptRequest(`/attempts/${id}`,{method:"PATCH",body:JSON.stringify({solution_markdown:solution,elapsed_seconds:elapsed,expected_revision:revision})});
export const submitAttempt=(id:string,revision:number)=>attemptRequest(`/attempts/${id}/submit`,{method:"POST",body:JSON.stringify({expected_revision:revision})});
