import type { CurriculumMetadata, ProblemDetail, ProblemSource, ProblemSummary, SelectionResult } from "./types";
type WireSummary={id:string;title:string;subtitle?:string;curriculum:{level:string;difficulty:number};estimated_minutes?:number;year?:number;topics:string[];source:ProblemSource};type WireDetail=WireSummary&{statement:string;hint_levels:number[];prerequisites:string[];skills:string[];resources?:ProblemDetail["resources"]};const API_BASE="/api";async function request<T>(path:string):Promise<T>{const response=await fetch(`${API_BASE}${path}`,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`API request failed (${response.status})`);return response.json() as Promise<T>}function summary(value:WireSummary):ProblemSummary{return{id:value.id,title:value.title,subtitle:value.subtitle,curriculum:value.curriculum,estimatedMinutes:value.estimated_minutes,year:value.year,topics:value.topics,source:value.source}}export async function getProblems(){return(await request<WireSummary[]>("/problems")).map(summary)}export async function getProblem(id:string):Promise<ProblemDetail>{const value=await request<WireDetail>(`/problems/${encodeURIComponent(id)}`);return{...summary(value),statement:value.statement,hintLevels:value.hint_levels,prerequisites:value.prerequisites,skills:value.skills,resources:value.resources}}
export const getCurriculum=()=>request<CurriculumMetadata>("/curriculum");
export type InferenceStatus={provider:string;status:"disabled"|"starting"|"loading"|"ready"|"unavailable"|"error";model:string;backend:string;quantization:string;latency_ms?:number;reason?:"provider_disabled"|"connection_failed"|"model_loading"|"unexpected_http_status"|"invalid_configuration"|null};
export const getInferenceStatus=()=>request<InferenceStatus>("/inference/status");
export type InferenceDiagnostics={provider:string;model:string;quantization:string;status:string;reason:string|null;checks:{provider_config:string;dns:string;tcp:string;health:string;models_endpoint:string}};
async function diagnosticRequest<T>(path:string,token:string,method="GET"):Promise<T>{const response=await fetch(`${API_BASE}${path}`,{method,headers:{Accept:"application/json","X-Diagnostics-Token":token}});if(!response.ok)throw new Error(response.status===401?"Jeton de diagnostics invalide.":`Diagnostic indisponible (${response.status})`);return response.json() as Promise<T>}
export const getDiagnostics=(token:string)=>diagnosticRequest<InferenceDiagnostics>("/diagnostics/inference",token);
export const getDiagnosticLogs=(source:"application"|"inference",token:string)=>diagnosticRequest<{source:string;lines:string[];available:boolean}>(`/diagnostics/logs?source=${source}&lines=200`,token);
export const testInference=(token:string)=>diagnosticRequest<{status:string;latency_ms:number;response_preview:string}>("/diagnostics/inference/test",token,"POST");
export async function selectProblem(level:string,difficulty:number,topic?:string,exclude?:string[]):Promise<SelectionResult>{const query=new URLSearchParams({level,difficulty:String(difficulty)});if(topic)query.append("topic",topic);exclude?.forEach(id=>query.append("exclude",id));const value=await request<{problem:WireDetail|null;requested_level:string;requested_difficulty?:number;actual_difficulty?:number;fallback_used:boolean}>(`/problems/select?${query}`);return{...value,problem:value.problem?{...summary(value.problem),statement:value.problem.statement,hintLevels:value.problem.hint_levels,prerequisites:value.problem.prerequisites,skills:value.problem.skills,resources:value.problem.resources}:null}}

import type { Attempt } from "./types";
import type { Evaluation } from "./types";
export class ApiError extends Error { constructor(public status:number, public payload?:{error?:string;current_revision?:number}){super(payload?.error??`API request failed (${status})`)} }
async function attemptRequest(path:string,init?:RequestInit):Promise<Attempt>{const response=await fetch(`${API_BASE}${path}`,{...init,headers:{Accept:"application/json","Content-Type":"application/json",...init?.headers}});const data=await response.json();if(!response.ok)throw new ApiError(response.status,data);return data}
export const createAttempt=(problemId:string)=>attemptRequest("/attempts",{method:"POST",body:JSON.stringify({problem_id:problemId})});
export const getAttempt=(id:string)=>attemptRequest(`/attempts/${id}`);
export const patchAttempt=(id:string,solution:string,elapsed:number,revision:number)=>attemptRequest(`/attempts/${id}`,{method:"PATCH",body:JSON.stringify({solution_markdown:solution,elapsed_seconds:elapsed,expected_revision:revision})});
export const submitAttempt=(id:string,revision:number)=>attemptRequest(`/attempts/${id}/submit`,{method:"POST",body:JSON.stringify({expected_revision:revision})});
async function evaluationRequest(path:string,method="GET"):Promise<Evaluation>{const response=await fetch(`${API_BASE}${path}`,{method,headers:{Accept:"application/json","Content-Type":"application/json"}});const data=await response.json();if(!response.ok)throw new ApiError(response.status,data);return data}
export const createEvaluation=(id:string)=>evaluationRequest(`/attempts/${id}/evaluation`,"POST");
export const retryEvaluation=(id:string)=>evaluationRequest(`/attempts/${id}/evaluation/retry`,"POST");

export type ReferenceSolution={problem_id:string;title:string;reference_solution:string};
export const getReferenceSolution=(id:string)=>request<ReferenceSolution>(`/attempts/${id}/reference-solution`);
